### PR TITLE
French Translation Update

### PR DESCRIPTION
**Pull request by Samlegamer**

### CODE REVIEW

**Comment by JMilamber** [comment]
leaving this open so you can just edit it and then I will merge it, (See translation-help issue for explanation)

**Comment by Samlegamer** [comment]
I don't know but it seems to me that there is a mistake here
ff

**Comment by JMilamber** [comment]
Definitely is! Thanks for catching that :)

**Comment by JMilamber** [comment]
Fixed now! I also added tooltips for the two chest blocks. xD 
Sorry, last addition for now I swear!

**Pull request merged**
