### PR TITLE
Italian localisation update

### PR DESCRIPTION
**Pull request by BlackShadow77**
Working on italian translations update

### CODE REVIEW

**Comment by BlackShadow77** [comment]
Hi, i'm updating italian localisation but i need some more context at line 112 and at line 114 ("Dungeons")

**Comment by BlackShadow77** [comment]
I also notice lines 76-81 are ordered in a different way in the EN file and i put them in a new order to keep coerence in the file

**Comment by JMilamber** [comment]
> Hi, i'm updating italian localisation but i need some more context at line 112 and at line 114 ("Dungeons")

Line 114 
"I will make you ROT in my DUNGEONS for this!..."

All of these lines (golem eye tooltips) are lore for essentially the Golem's last words as it dies. 
Here the words "rot" and "dungeons" are capitalized to imitate shouting. 

The line here is implying that the Nether Golem will get revenge and imprison the player in his "dungeons" referring to a not-yet created prison room in the Nether tower. 

Hope that helps!

**Comment by BlackShadow77** [comment]
> The line here is implying that the Nether Golem will get revenge and imprison the player in his "dungeons" referring to a not-yet created prison room in the Nether tower.

Thanks, that help a lot the localisation, can u also give some context to line 112? (_"Praise the void... Praise me..."_)

**Comment by JMilamber** [comment]
Yeah! Line 112 "Praise the void... Praise me..." 

Here the Ocean Golem is referencing the fact that they are in fact a void creature.
The void can be generally considered the space between dimensions. "Void" of all life/matter (at least in terms of our understanding of matter).

In vanilla Minecraft Endermen would be the closest you see to a "void" creature, though since the End biome has structures and blocks it can't truly be considered a void. 

Most "void" creatures in fantasy have powers that use "void energy" essentially a type of energy that is bound by rules that we cannot comprehend (when compared to say electricity or magic) and those powers make many fantasy cultures consider them "gods". Void creatures also typically worship the "void" itself as their "god" (hence "praise the void"). 

In BT lore, only the Core and Sky golem are actual gods, but the ocean golem (being a void creature and immensely powerful) falsely believes itself to be a God and this calls on the player to worship it ("Praise me...").

**Comment by BlackShadow77** [comment]
I finished all work on it, i guess.
Thanks for the work you put on this mod, i really like it.
Check if i need to change something else and then i'll mark this request as ready.

**Comment by JMilamber** [comment]
Looks good, sorry this took so long, I saw it, looked at it, forgot to message on it, and then completely forgot about it till now XD

A few new lines in the recent commit for ocean chest/spawners. Once those are good feel free to submit it! 
Thanks for your support!

**Comment by BlackShadow77** [comment]
i'll update translations and wait for your confermation to mark this as ready to merge

**Comment by BlackShadow77** [comment]
As commented [here](https://github.com/BlackShadow77/Brass_Amber_BattleTowers/commit/831dc0692b63a0e88d738ed2593e6fb1c9081662#commitcomment-74481699) 2 lines have same name to different object, can i suggest to directly change "Golem Chest" to "*name of golem*'s chest"?

To be more clear, an example:
` "block.ba_bt.land_golem_chest": "Golem Chest" ` --> ` "block.ba_bt.land_golem_chest": "Bahryn'muul's Chest" `

**Comment by JMilamber** [comment]
Good call, I'll edit Lang files tonight.

**Comment by BlackShadow77** [comment]
Great! I'll already translate that. In this way you can say if i can finally mark this as ready for review

**Comment by BlackShadow77** [comment]
I updated all files and changed lines 49, 52, 66, 67, 71, 72 with names as written before. (Already translated)

**Pull request merged**
