### PR TITLE
Updating italian localisation

### PR DESCRIPTION
**Pull request by BlackShadow77**
Working on italian translation files

### CODE REVIEW

**Comment by BlackShadow77** [comment]
@JMilamber when you have some free time i need some context to strings 130 and 133 about the depth dropper

**Comment by JMilamber** [comment]
@BlackShadow77  The Enchantment Is just how the affect is applied to the player so I will explain the Effect -

The effect is applied to the player due to the power of The Ocean Golem being from the void, and so the "pressure" down in the trench pulls you downwards like gravity.

So when the effect is active you move downwards continuously(if in water) at around the same rate as you would falling from a cliff to the ground. 
"Depth Dropper" then is referring to the fact that you drop/fall/sink downwards to the depths/deep/bottom of the ocean. 

Depth/depths here is referring to what we cal the Ocean Depths in English which usually refer to the incredibly deep trenches out in the Ocean that you need a special submarine to go into and are almost pitch black at the bottom.

In the future, we plan to rework the effect so that it makes you unable to swim, but walk and jump like you are not underwater as well as having a slight vision impairment. 

Let me know if I can elaborate more about anything :) or if I have just been more confusing with this explanation xD.

**Comment by BlackShadow77** [comment]
@JMilamber If i understood well the effect refers to a deep ocean state where u're heavy and the pressure is huge (this about the special submarine). I still don't understand the rework to the effect because if u're under high pressure maybe u should also wear a special suite to keep u alive; but this is another topic.

In conclusion this is a negative effect applied to the player that make u heavy and grab him to the center of the heart, am i right?

**Comment by BlackShadow77** [comment]
Update: i need some more context in others strings.
Line 206: "Void Beast of the Abyss", especially _Void Beast_.
Lines 170-171, 176-177, 182-183: sounds weird in italian, i can't see the link between the first sentence and the second one in terms of coerence. 
I hope i explained myself well, it's late. Tell me if you need more explanations.

**Comment by JMilamber** [comment]
Lines 7 and 206 have been changed entirely, after looking at them _Void Beast_ really didn't make sense  xD
Hmmm, I see how those don't really go together as one sentence. More like 2 separate pieces.

I Have updated those lines as well to make more sense (hopefully) as sentences, let me know if they ned explaining

**Comment by BlackShadow77** [comment]
Hi!

Happy new year, i hope to see the next version of the mod this year. i'm excited about this mod because i see all of the ideas and work you put on it and i really wish to see that completed asap!


Regarding your last comment i didn't notice changes to lines 7 and 206, i updated the translation to fix it; i also worked on lines 195 and 196 because i noticed some changes in the original file and i like more the new version so i did a new tralsation for that.


About lines 170-171, 176-177 and 182-183 (now lines 177-178, 183-184 and 189-190) i still see some problems.
In my opinion line 178 can be something concerning the depths or the void, something like "..the floor is getting absorbed by the void" _(and on animation side u can change the usual explosion effect to one that simply drag blocks to the ground; something similar to a trasformation of the tower in sand or gravel so u get squashed between blocks if u don't run in a similar way as u described the new effect.. but this sounds complicated in code so i'll let that only as an idea)_

Also line 184, there is a plan to change explosion of nether tower with a surprising harmless trasfromation of nether bricks in grass and flowers? I need more context on this.

At last on line 190 i think the entire sentence should be changed. I can suggest something like "A goddess can't accept to die to a mere player... with her last drop of power she try to drag you in the death realm" or "A goddess killed by a mere player... also the tower can't accept her fate!". I don't know if these sentence fits the right spots but seems a reasonable start for a change in lines 189-190 in my opinion.


Sorry if i wrote something rude to you, i just want to do a well made translation for this fantastic mod so i want to understand the idea behind your words.
I'm waiting for any update!

Have a nice day and a cloudless new year!

**Comment by JMilamber** [comment]
No worries! Changes to 7 and 206 were made after your comment, all your questions help make the mod better :)
Nothing rude! 

About line 178: The newest update includes the Ocean Tower "destruction" in which the entire tower falls into the void from the bottom up, leaving a giant hole from sea level down through bedrock. Which is why the second line is "crumble" currently. So your suggestion is spot on. 

> Also line 184, there is a plan to change explosion of nether tower with a surprising harmless trasfromation of nether bricks in grass and flowers? I need more context on this.
Yep! Current Idea is that most of the tower returns to a more "wild" state without the restrictive/controlling nether tyrant.
"Blooming" here refers to the tower turning into a mini-jungle taking inspiration from the newer nether biomes, 

Changed 189/190, think it works better now.
Idea is that the sky tower will just disappear (Like the Land tower but in smaller more condensed chunks and no explosions, just blocks disappearing)

Happy New Year!

**Comment by JMilamber** [comment]
Also I appreciate the Readme Fix 👍

**Comment by BlackShadow77** [comment]
Hi!
Happy to hear a "simple translator" can be impactfull in the developing of a mod like that; ty for the kind words!

Regarding translations:
i updated all italian translations to the branch so i think they are ready for the merge untill your next update!

Again, thank you for the patience and the work on this project.

See you next update!

(i literally added some spaces in readme file so it was nothing compared your work!)

**Pull request merged**
